apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nomios.fullname" . }}
  labels:
    app: {{ template "nomios.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: {{ .Values.event.type }}
    kind: {{ .Values.event.kind }}
    discovery: "event-provider"
data:
  # always regenerate random token - leads to shanged SHA256 sum and thus Deployment recreate
  random_token: {{ randAlphaNum 10 | b64enc | quote }}
  # DockerHub trigger type configuration
  config.json: |
  {{ .Files.Get "config.json.txt" | indent 4 }}
